name: CI Angular app through Github Actions
on:
  pull_request:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'   #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './dist/*'  # 对应我们项目build的文件夹路径
          remote_path: '/root/www/angular-app'
